service: email-service

provider:
  name: aws
  runtime: python3.12
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

functions:
  sendEmail:
    handler: EmailService/handler.send_email
    events:
      - http:
          path: send-email
          method: post 